config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from debug_toolbar import urls as debug_toolbar_urls

from system.views import home, login, logout

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('mailing/', include('mailing.urls')),
    path('pioneering/', include('pioneering.urls')),
    path('publishers/', include('publishers.urls')),
    path('reports/', include('reports.urls')),
    path('servants/', include('servants.urls')),
    path('login/', login, name='system-login'),
    path('logout/', logout, name='system-logout'),
    path('', include('system.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar_urls))
    ]

congregationms/mailing/urls.py
from django.urls import path

from .views import MailCreateView

app_name = 'mailing'
urlpatterns = [
    path('new/<str:publisher>', MailCreateView.as_view(), name='new'),
]

congregationms/publishers/urls.py
from django.urls import path

from .views import (
    PublisherCreate, PublisherDelete, PublisherDetail,
    PublisherList, PublisherUpdate, GroupCreate, GroupDetail, GroupList, GroupUpdate
)


app_name = 'publishers'
urlpatterns = [
    path('', PublisherList.as_view(), name='index'),
    path('groups/', GroupList.as_view(), name='group-index'),
    path('groups/new/', GroupCreate.as_view(), name='group-create'),
    path('groups/detail/<str:pk>/', GroupDetail.as_view(), name='group-detail'),
    path('groups/edit/<str:pk>/', GroupUpdate.as_view(), name='group-update'),
    path('edit/<slug:slug>/', PublisherUpdate.as_view(), name='update'),
    path('detail/<slug:slug>/', PublisherDetail.as_view(), name='detail'),
    path('new/', PublisherCreate.as_view(), name='create'),
    path('delete/<str:pk>/', PublisherDelete.as_view(), name='delete')
]

congregationms/reports/urls.py
from django.urls import path

from .views import (
    InfirmedListView, MFSCreate, MFSDelete, MFSDetail, MFSList, MFSUpdate,
    MFSHistoryList, PioneerListView, sample_mfs, ServantListView,
    ShareToRedirectView, InactivePublisherListView
)

app_name = 'reports'
urlpatterns = [
    path('monthly-field-service/', MFSList.as_view(), name='mfs-index'),
    path('monthly-field-service/history/publisher/<slug:publisher>/',
         MFSHistoryList.as_view(), {'view_type': 'publisher'},
         name='mfs-history'),
    path('monthly-field-service/history/group/<str:group>/',
         MFSHistoryList.as_view(), {'view_type': 'group'},
         name='mfs-history-group'),
    path('monthly-field-service/delete/<str:pk>/',
         MFSDelete.as_view(), name='mfs-delete'),
    path('monthly-field-service/new/', MFSCreate.as_view(), name='mfs-create'),
    path('monthly-field-service/<str:pk>/',
         MFSDetail.as_view(), name='mfs-detail'),
    path('monthly-field-service/update/<str:pk>/',
         MFSUpdate.as_view(), name='mfs-update'),


    path('mfs/download/group/<str:pk>/', sample_mfs, name='mfs-download'),
    path('mfs/<str:publisher>/share-to/',
         ShareToRedirectView.as_view(), name='share_to'),

    path(
        'publishers/inactive/',
        InactivePublisherListView.as_view(),
        name='publishers_inactive'),
    path(
        'publishers/<str:view_type>/',
        InfirmedListView.as_view(),
        name='publishers'),

    path(
        'pioneering/<str:view_type>/',
        PioneerListView.as_view(),
        name='pioneering'),

    path(
        'servants/<str:view_type>/',
        ServantListView.as_view(),
        name='servants'),
]

congregationms/system/urls.py
from django.urls import path

from .views import dashboard, AccountView

app_name = 'system'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('account/', AccountView.as_view(), name='account'),
]

congregationms/urls.py
from django.contrib import admin
from django.urls import path

from system.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
]

congregationms/system/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

from .helpers import SingletonModel


class User(AbstractUser):
    pass


class Congregation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name


class Setting(SingletonModel):
    initial_data_runned = models.BooleanField(default=False, blank=True)

congregationms/mailing/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.edit import CreateView

from .forms import MailModelForm
from .models import Mail


class MailCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Receive query params [filename]."""
    form_class = MailModelForm
    model = Mail
    permission_required = ('mailing.add_mail',)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial = initial.copy()
        initial['attachment'] = self.request.GET.get('filename')
        return initial

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:index')

    def form_valid(self, form):
        _value = super().form_valid(form)

        if form.send_email():
            messages.success(
                self.request,
                'Successfully shared via email!')
        else:
            message = 'Something went wrong. Unable to share via \
                        email. Please check your internet connection.'
            messages.error(self.request, message)
            return HttpResponseRedirect(self.request.GET.get('on_fail'))
        return _value

congregationms/pioneering/views.py
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PioneerDetailFormSet, PioneerModelForm
from .models import Pioneer
from publishers.utils import get_user_groups_members
from system.utils import (
    LoginAndPermissionRequiredMixin, AddUserToFormMixin, AddRequestToForm)


class PioneerListView(LoginAndPermissionRequiredMixin, ListView):
    model = Pioneer
    context_object_name = 'pioneers'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Pioneer.objects.filter(publisher__in=auth_pubs)
            queryset = queryset.select_related('publisher')
        else:
            queryset = self.model.objects.none()

        return queryset


class PioneerDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Pioneer
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        q = super().get_queryset()
        q = q.prefetch_related('details', 'publisher')
        return q


class PioneerCreateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, CreateView):
    model = Pioneer
    form_class = PioneerModelForm
    permission_required = ('pioneering.add_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(self.request.POST)
        else:
            data['details'] = PioneerDetailFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                self.object = form.save()
                details.instance = self.object
                details.save()

        messages.success(
            self.request,
            'Successfully created new pioneer. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('pioneering:update', args=[str(self.object.code)])


class PioneerUpdateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, UpdateView):
    model = Pioneer
    form_class = PioneerModelForm
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.change_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(
                self.request.POST, instance=self.object)
        else:
            data['details'] = PioneerDetailFormSet(instance=self.object)
        data['is_active'] = self.object.is_active
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                details.instance = self.object
                details.save()
                self.object = form.save()

        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PioneerDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Pioneer
    success_url = reverse_lazy('pioneering:index')
    permission_required = ('pioneering.delete_pioneer',)

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()

congregationms/publishers/views.py
#from django.shortcuts import render
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import GroupModelForm, GroupMemberFormSet, PublisherModelForm
from .models import Group, Publisher, Member
from .utils import get_publishers_as_choices
from system.utils import LoginAndPermissionRequiredMixin


# Create your views here.
class PublisherList(LoginAndPermissionRequiredMixin, ListView):
    model = Publisher
    permission_required = 'publishers.view_publisher',

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Publisher.objects.filter(id__in=auth_pubs)
        else:
            queryset = self.model.objects.none()

        return queryset


class PublisherUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Publisher
    form_class = PublisherModelForm
    context_object_name = 'publisher'
    permission_required = 'publishers.change_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PublisherDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Publisher
    context_object_name = 'publisher'
    permission_required = 'publishers.view_publisher',


class PublisherCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Publisher
    form_class = PublisherModelForm
    permission_required = 'publishers.add_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully created new publisher. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:update', args=[str(self.object.slug)])


class PublisherDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Publisher
    success_url = reverse_lazy('publishers:index')
    permission_required = 'publishers.delete_publisher',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupList(LoginAndPermissionRequiredMixin, ListView):
    model = Group
    permission_required = 'publishers.view_group',

    def get_queryset(self):
        queryset = self.model.objects.none()

        # user = self.request.user
        # publisher = user.publisher
        # group = publisher.group_members.filter(is_active=True)
        # group = group.first()  # publishers.Member object
        # if group:
        #     queryset = super().get_queryset()
        #     queryset = queryset.filter(id=group.group_id)
        groups = self.request.authorized_groups  # publisher.UserGroup objects
        if groups:
            groups = [g.group_id for g in groups]  # Group pks
            queryset = super().get_queryset().filter(id__in=groups)
            queryset = queryset.select_related('congregation')

        return queryset


class GroupDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Group
    context_object_name = 'group'
    permission_required = 'publishers.view_group',


class GroupUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Group
    form_class = GroupModelForm
    context_object_name = 'group'
    permission_required = 'publishers.change_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST, instance=self.object)
        else:
            formset = GroupMemberFormSet(instance=self.object)

        data['members'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully edited Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)


class GroupDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('publishers:group-index')
    permission_required = 'publishers.delete_group',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Group
    form_class = GroupModelForm
    permission_required = 'publishers.add_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST)
        else:
            formset = GroupMemberFormSet()

        data['members'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully created new Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)

congregationms/servants/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ServantModelForm
from .models import Servant
from system.utils import LoginAndPermissionRequiredMixin


class ServantListView(LoginAndPermissionRequiredMixin, ListView):
    model = Servant
    permission_required = 'servants.view_servant',

    def get_queryset(self):
        return super().get_queryset().select_related('publisher')


class ServantCreateView(LoginAndPermissionRequiredMixin, CreateView):
    model = Servant
    form_class = ServantModelForm
    permission_required = 'servants.add_servant'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mode'] = 'New'
        return context


class ServantDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Servant
    permission_required = 'servants.view_servant',

    def get_queryset(self):
        return super().get_queryset().select_related('publisher')


class ServantDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Servant
    permission_required = 'servants.delete_servant',
    success_url = reverse_lazy('servants:index')


class ServantUpdateView(LoginAndPermissionRequiredMixin, UpdateView):
    model = Servant
    form_class = ServantModelForm
    permission_required = 'servants.change_servant',

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mode'] = 'Edit'
        return context

    def get_queryset(self):
        q = super().get_queryset()
        q = q.select_related('publisher')

        return q

congregationms/templates/publishers/base.html
{% extends "base.html" %}


{% block breadcrumbs %}
  <li><a href='{% url "publishers:index" %}'>Publishers</a></li>
  {% block subbreadcrumbs %}{% endblock subbreadcrumbs %}
{% endblock breadcrumbs %}

{% block navbaritems %}
  {% include "_snippets/navbar_items.html" with publishers_active='is-active' %}
{% endblock navbaritems %}

{% block aside_menu %}
  {% include "aside.html" with publishers_active='is-active' %}  
{% endblock aside_menu %}

{% block main %}
<div class="content">
  {% block content %}{% endblock content %}  
</div>
{% endblock main %}

congregationms/templates/publishers/base_group.html
{% extends "publishers/base.html" %}

{% block subbreadcrumbs %}
	<li><a href="{% url 'publishers:group-index' %}">Groups</a></li>
	{% block groupbreadcrumbs %}{% endblock groupbreadcrumbs %}
{% endblock subbreadcrumbs %}

{% block aside_menu %}
  {% include "aside.html" with publishers_groups_active='is-active' %}  
{% endblock aside_menu %}

congregationms/templates/publishers/group_detail.html
{% extends "publishers/base_group.html" %}

{% block title %}
  <title>Group Detail | {{group|title}}</title>  
{% endblock title %}

{% block groupbreadcrumbs %}
	<li><a href="#">{{group|title}}</a></li>	
	<li class="is-active">Detail</li>	
{% endblock groupbreadcrumbs %}

{% block content %}
  <h1>Group Detail</h1>

  <div class="field is-grouped is-pulled-right">

    <div class="control">
      <a href='{% url "publishers:group-update" group.pk %}'><button class="button is-outlined">{% include "_snippets/icon_edit.html" %}</button></a>
    </div>
  </div>
  
  <p class="is-size-3">{{ group|upper }}</p>
  <p><a href='{% url "reports:mfs-history-group" group.pk %}'>View MFS history</a></p>
  <p>Congregation: {{ group.congregation }}</p>

  <section>
    <h2 class="is-size-5">Members:</h2>
    {% include "publishers/snippets/publisher_table_list.html" with object_list=group.members %}
  </section>
{% endblock content %}

congregationms/templates/publishers/group_form.html
{% extends "publishers/base_group.html" %}

{% block title %}
  {% if group %}
    <title>Group Edit | {{group|title}}</title>  
  {% else %}
    <title>Group New</title>  
  {% endif %}
{% endblock title %}

{% block groupbreadcrumbs %}
  {% if  group %}
    <li><a href='{% url "publishers:group-detail" group.pk %}'>{{ group|title }}</a></li>
  	<li class="is-active"><a href='#'>Edit</a></li>  
  {% else %}
  	<li class="is-active"><a href='#'>New</a></li>  
  {% endif %}
{% endblock groupbreadcrumbs %}

{% block content %}
  {% if  group %}
    <h1>Group Edit</h1>
    <p class="is-size-3">Edit Group</p>
  {% else %}
    <h1>Group New</h1>
    <p class="is-size-3">Create a New Group</p>  
  {% endif %}

    <form method="POST">
      {% csrf_token %}
      <div class="field">
        <label class="label">Name</label>
        <div class="control">
          <input class="input" type="text" name="name" value="{{ group.name}}" required>
        </div>
      </div>

      <div class="field">
        <label class="label">Congregation</label>
        <div class="control">
        	<div class="select is-fullwidth">
        		{{form.congregation}}
        	</div>
        </div>
      </div>

      {# group members #}
      <section>
        <h2>Members</h2>
        {{ members.management_form }}
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th class="has-text-centered">Publisher</th>
              <th class="has-text-centered">Active</th>
              <th class="has-text-centered">From</th>
              <th class="has-text-centered">To</th>
              <th class="has-text-centered">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for form in members %}
              <tr>
                <td>
                  <div class="select is-fullwidth">
                    {{form.publisher}}
                  </div>
                </td>

                <td class="has-text-centered">
                  <label class="checkbox" for="{{form.is_active.id_for_label}}">
                    <input type="checkbox" name="{{form.is_active.html_name}}" id="{{form.is_active.id_for_label}}" {% if form.is_active.value %}checked="{{form.is_active.value}}"{% endif %}>
                  </label>
                </td>

                <td>
                  <input class="input is-fullwidth" type="date" name="{{form.date_from.html_name}}" id="{{form.date_from.id_for_label}}" value="{{form.date_from.value|date:'Y-m-d'}}">
                </td>

                <td>
                  <input class="input is-fullwidth" type="date" name="{{form.date_to.html_name}}" id="{{form.date_to.id_for_label}}" value="{{form.date_to.value|date:'Y-m-d'}}">
                  {{form.id}}
                  {{form.group}}
                </td>
                <td>
                  {% if members.can_delete %}
                    {{form.DELETE}} 
                  {% else %}
                    <input type="checkbox" disabled>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>

      {% if group %}
        {% include "_snippets/button_save.html" %}
      {% else %}
        {% include "_snippets/button_create.html" %}
      {% endif %}
    </form>
{% endblock content %}

congregationms/templates/publishers/group_list.html
{% extends "publishers/base_group.html" %}

{% block title %}
  <title>Groups</title>  
{% endblock title %}

{% block groupbreadcrumbs %}
	<li class="is-active">List</li>	
{% endblock groupbreadcrumbs %}

{% block content %}
  <h1>Group List</h1>
	<a href='{% url "publishers:group-create" %}'>{% include "_snippets/button_new.html" %}</a>
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th>Congregation</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for group in object_list %}
        <tr>
          <td>{{ group.name|title }}</td>
          <td>{{ group.congregation|title }}</td>
          <td>
            <a href='{% url "publishers:group-detail" group.pk %}'><span class="button is-outlined">{% include "_snippets/icon_view.html" %}</span></a>
            <a href='{% url "publishers:group-update" group.pk %}'><span class="button is-outlined">{% include "_snippets/icon_edit.html" %}</span></a>
            <a href='{% url "reports:mfs-history-group" group.pk %}'><button class="button is-outlined">{% include "_snippets/icon_view.html" %}<span>&nbspMFS history</span></button></a>
          </td>
        </tr>
      {% endfor %}
      {% if not object_list %}
        <tr>
          <td class="has-text-centered" colspan="3">No data available. Please <a href="{% url 'publishers:group-create' %}"><u>add</u></a></td>
        </tr>
      {% endif %}
    </tbody>
  </table>
{% endblock content %}

congregationms/templates/publishers/publisher_detail.html
{% extends "publishers/base.html" %}
{% load static %}

{% block title %}
  <title>Publisher Detail | {{publisher.name|title}}</title>
{% endblock title %}

{% block subbreadcrumbs %}
  <li class="is-active"><a href='#'>Detail</a></li>  
{% endblock subbreadcrumbs %}

{% block content %}
  <h1>Publisher Detail</h1>

  <div class="field is-grouped is-pulled-right" id="delete-button-app">
    <div class="control">
      <form id="form--{{ publisher.pk }}" action='{% url "publishers:delete" publisher.pk %}' method="POST" @submit.prevent="confirmDelete">
        {% csrf_token %}
        <button class="button is-outlined" type="submit" form="form--{{ publisher.pk }}" :disabled="disabled">{% include "_snippets/icon_trash.html" %}</button>
      </form>
    </div>

    <div class="control">
      <a href='{% url "publishers:update" publisher.slug %}'><button class="button is-outlined">{% include "_snippets/icon_edit.html" %}</button></a>
    </div>
  </div>
  
  <p class="is-size-3">{{ publisher.name|upper }}</p>
  <p><a href='{% url "reports:mfs-history" publisher.slug %}'>View MFS history</a></p>
  <p>Date of Birth: {{ publisher.date_of_birth }}</p>
  <p>Date of Baptism: {{ publisher.date_of_baptism }}</p>
  <p>Contact Numbers: {{ publisher.contact_numbers }}</p>
  <p>Group: {{ publisher.group|title }}</p>
  <p>Infirmed: {% if publisher.infirmed %}{% include "_snippets/icon_check.html" %}{% else %}{% include "_snippets/icon_times.html" %}{% endif %}</p>
  <p>Elderly: {% if publisher.elderly %}{% include "_snippets/icon_check.html" %}{% else %}{% include "_snippets/icon_times.html"  %}{% endif %}</p>
{% endblock content %}

{% block vueinstance %}
    <script src="{% static "deleteButtonApp.js" %}"></script>
{% endblock vueinstance %}

congregationms/templates/publishers/publisher_list.html
{% extends "publishers/base.html" %}

{% block title %}
  <title>Publishers</title>  
{% endblock title %}

{% block content %}
  <h1>Publishers List</h1>
  <a href='{% url "publishers:create" %}'>{% include "_snippets/button_new.html" %}</a>

  {% include "publishers/snippets/publisher_table_list.html" %}
{% endblock content %}