config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from debug_toolbar import urls as debug_toolbar_urls

from system.views import home, login, logout

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('mailing/', include('mailing.urls')),
    path('pioneering/', include('pioneering.urls')),
    path('publishers/', include('publishers.urls')),
    path('reports/', include('reports.urls')),
    path('servants/', include('servants.urls')),
    path('login/', login, name='system-login'),
    path('logout/', logout, name='system-logout'),
    path('', include('system.urls')),
    path('', home, name='home'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar_urls))
    ]

congregationms/mailing/urls.py
from django.urls import path

from .views import MailCreateView

app_name = 'mailing'
urlpatterns = [
    path('new/<str:publisher>', MailCreateView.as_view(), name='new'),
]

congregationms/pioneering/urls.py
from django.urls import path

from .views import (PioneerCreateView, PioneerDeleteView, PioneerDetailView,
                    PioneerListView, PioneerUpdateView)


app_name = 'pioneering'
urlpatterns = [
    path('detail/<slug:slug>/', PioneerDetailView.as_view(), name='detail'),
    path('new/', PioneerCreateView.as_view(), name='create'),
    path('edit/<slug:slug>/', PioneerUpdateView.as_view(), name='update'),
    path('delete/<str:pk>/', PioneerDeleteView.as_view(), name='delete'),
    path('', PioneerListView.as_view(), name='index'),
]

congregationms/system/urls.py
from django.urls import path

from .views import dashboard, AccountView

app_name = 'system'
urlpatterns = [
    path('dashboard', dashboard, name='dashboard'),
    path('account/', AccountView.as_view(), name='account'),
]

congregationms/urls.py
from django.contrib import admin
from django.urls import path

from system.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
]

congregationms/system/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models

from .helpers import SingletonModel


class User(AbstractUser):
    pass


class Congregation(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name


class Setting(SingletonModel):
    initial_data_runned = models.BooleanField(default=False, blank=True)

congregationms/mailing/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.edit import CreateView

from .forms import MailModelForm
from .models import Mail


class MailCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Receive query params [filename]."""
    form_class = MailModelForm
    model = Mail
    permission_required = ('mailing.add_mail',)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial = initial.copy()
        initial['attachment'] = self.request.GET.get('filename')
        return initial

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:index')

    def form_valid(self, form):
        _value = super().form_valid(form)

        if form.send_email():
            messages.success(
                self.request,
                'Successfully shared via email!')
        else:
            message = 'Something went wrong. Unable to share via \
                        email. Please check your internet connection.'
            messages.error(self.request, message)
            return HttpResponseRedirect(self.request.GET.get('on_fail'))
        return _value

congregationms/pioneering/views.py
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import PioneerDetailFormSet, PioneerModelForm
from .models import Pioneer
from publishers.utils import get_user_groups_members
from system.utils import (
    LoginAndPermissionRequiredMixin, AddUserToFormMixin, AddRequestToForm)


class PioneerListView(LoginAndPermissionRequiredMixin, ListView):
    model = Pioneer
    context_object_name = 'pioneers'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Pioneer.objects.filter(publisher__in=auth_pubs)
            queryset = queryset.select_related('publisher')
        else:
            queryset = self.model.objects.none()

        return queryset


class PioneerDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Pioneer
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.view_pioneer',)

    def get_queryset(self):
        q = super().get_queryset()
        q = q.prefetch_related('details', 'publisher')
        return q


class PioneerCreateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, CreateView):
    model = Pioneer
    form_class = PioneerModelForm
    permission_required = ('pioneering.add_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(self.request.POST)
        else:
            data['details'] = PioneerDetailFormSet()

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                self.object = form.save()
                details.instance = self.object
                details.save()

        messages.success(
            self.request,
            'Successfully created new pioneer. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('pioneering:update', args=[str(self.object.code)])


class PioneerUpdateView(
        AddRequestToForm, LoginAndPermissionRequiredMixin, UpdateView):
    model = Pioneer
    form_class = PioneerModelForm
    context_object_name = 'pioneer'
    slug_field = 'code'
    permission_required = ('pioneering.change_pioneer',)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['details'] = PioneerDetailFormSet(
                self.request.POST, instance=self.object)
        else:
            data['details'] = PioneerDetailFormSet(instance=self.object)
        data['is_active'] = self.object.is_active
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        details = context['details']

        with transaction.atomic():
            if details.is_valid():
                details.instance = self.object
                details.save()
                self.object = form.save()

        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PioneerDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Pioneer
    success_url = reverse_lazy('pioneering:index')
    permission_required = ('pioneering.delete_pioneer',)

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()

congregationms/publishers/views.py
#from django.shortcuts import render
from django.contrib import messages
from django.db import transaction
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import GroupModelForm, GroupMemberFormSet, PublisherModelForm
from .models import Group, Publisher, Member
from .utils import get_publishers_as_choices
from system.utils import LoginAndPermissionRequiredMixin


# Create your views here.
class PublisherList(LoginAndPermissionRequiredMixin, ListView):
    model = Publisher
    permission_required = 'publishers.view_publisher',

    def get_queryset(self):
        auth_pubs = self.request.authorized_publisher_pks
        if auth_pubs:
            queryset = Publisher.objects.filter(id__in=auth_pubs)
        else:
            queryset = self.model.objects.none()

        return queryset


class PublisherUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Publisher
    form_class = PublisherModelForm
    context_object_name = 'publisher'
    permission_required = 'publishers.change_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully updated.'
        )
        return super().form_valid(form)


class PublisherDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Publisher
    context_object_name = 'publisher'
    permission_required = 'publishers.view_publisher',


class PublisherCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Publisher
    form_class = PublisherModelForm
    permission_required = 'publishers.add_publisher',

    def form_valid(self, form):
        messages.success(
            self.request,
            'Successfully created new publisher. Continue editing other details'
        )
        return super().form_valid(form)

    def get_success_url(self, *args, **kwargs):
        return reverse('publishers:update', args=[str(self.object.slug)])


class PublisherDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Publisher
    success_url = reverse_lazy('publishers:index')
    permission_required = 'publishers.delete_publisher',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupList(LoginAndPermissionRequiredMixin, ListView):
    model = Group
    permission_required = 'publishers.view_group',

    def get_queryset(self):
        queryset = self.model.objects.none()

        # user = self.request.user
        # publisher = user.publisher
        # group = publisher.group_members.filter(is_active=True)
        # group = group.first()  # publishers.Member object
        # if group:
        #     queryset = super().get_queryset()
        #     queryset = queryset.filter(id=group.group_id)
        groups = self.request.authorized_groups  # publisher.UserGroup objects
        if groups:
            groups = [g.group_id for g in groups]  # Group pks
            queryset = super().get_queryset().filter(id__in=groups)
            queryset = queryset.select_related('congregation')

        return queryset


class GroupDetail(LoginAndPermissionRequiredMixin, DetailView):
    model = Group
    context_object_name = 'group'
    permission_required = 'publishers.view_group',


class GroupUpdate(LoginAndPermissionRequiredMixin, UpdateView):
    model = Group
    form_class = GroupModelForm
    context_object_name = 'group'
    permission_required = 'publishers.change_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST, instance=self.object)
        else:
            formset = GroupMemberFormSet(instance=self.object)

        data['members'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully edited Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)


class GroupDelete(LoginAndPermissionRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('publishers:group-index')
    permission_required = 'publishers.delete_group',

    def get_success_url(self):
        messages.success(
            self.request,
            'Successfully deleted {}.'.format(str(self.object))
        )
        return super().get_success_url()


class GroupCreate(LoginAndPermissionRequiredMixin, CreateView):
    model = Group
    form_class = GroupModelForm
    permission_required = 'publishers.add_group',

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = GroupMemberFormSet(self.request.POST)
        else:
            formset = GroupMemberFormSet()

        data['members'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        members = context['members']

        with transaction.atomic():
            self.object = form.save()
            if members.is_valid():
                members.instance = self.object
                members.save()

        messages.success(
            self.request,
            'Successfully created new Group {}.'.format(str(self.object))
        )
        return super().form_valid(form)

congregationms/servants/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import ServantModelForm
from .models import Servant
from system.utils import LoginAndPermissionRequiredMixin


class ServantListView(LoginAndPermissionRequiredMixin, ListView):
    model = Servant
    permission_required = 'servants.view_servant',

    def get_queryset(self):
        return super().get_queryset().select_related('publisher')


class ServantCreateView(LoginAndPermissionRequiredMixin, CreateView):
    model = Servant
    form_class = ServantModelForm
    permission_required = 'servants.add_servant'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mode'] = 'New'
        return context


class ServantDetailView(LoginAndPermissionRequiredMixin, DetailView):
    model = Servant
    permission_required = 'servants.view_servant',

    def get_queryset(self):
        return super().get_queryset().select_related('publisher')


class ServantDeleteView(LoginAndPermissionRequiredMixin, DeleteView):
    model = Servant
    permission_required = 'servants.delete_servant',
    success_url = reverse_lazy('servants:index')


class ServantUpdateView(LoginAndPermissionRequiredMixin, UpdateView):
    model = Servant
    form_class = ServantModelForm
    permission_required = 'servants.change_servant',

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['mode'] = 'Edit'
        return context

    def get_queryset(self):
        q = super().get_queryset()
        q = q.select_related('publisher')

        return q

congregationms/system/views.py
from datetime import datetime

from django.contrib.auth import (
    authenticate, login as user_login, logout as user_logout)
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import TemplateView

from reports.utils import mfs_stats


class AccountView(TemplateView):
    template_name = 'system/account.html'


def home(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('system:dashboard'))
    else:
        return render(request, 'system/home.html')


def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home'))

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            user_login(request, user)
            next_url = request.GET.get('next', reverse('home'))

            message = 'Successfully logged in. Thank you! \
                        You can start working now.'
            messages.success(request, message)
            return HttpResponseRedirect(next_url)
        else:
            return render(request, 'system/login.html', context={
                'username': username,
                'password': password
            })
    else:
        return render(request, 'system/login.html')


def logout(request):
    user_logout(request)

    return HttpResponseRedirect(reverse('home'))


def dashboard(request):
    now = datetime.now().date()
    prev_month = now.month - 1
    year = now.year

    if prev_month == 0:
        prev_month = 12
        year -= 1
    context = mfs_stats(prev_month, now.year)
    return render(request, 'system/dashboard.html', context)

congregationms/templates/pioneering/base.html
{% extends "base.html" %}


{% block breadcrumbs %}
  <li><a href='{% url "pioneering:index" %}'>Pioneers</a></li>
  {% block subbreadcrumbs %}{% endblock subbreadcrumbs %}
{% endblock breadcrumbs %}

{% block navbaritems %}
  {% include "_snippets/navbar_items.html" with pioneering_active='is-active' %}
{% endblock navbaritems %}

{% block aside_menu %}
  {% include "aside.html" with pioneering_active='is-active' %}  
{% endblock aside_menu %}

{% block main %}
<div class="content">
  {% block content %}{% endblock content %}  
</div>
{% endblock main %}

congregationms/templates/pioneering/pioneer_detail.html
{% extends "pioneering/base.html" %}
{% load static %}

{% block title %}
  <title>Pioneer's Detail | {{pioneer.publisher.name|title}}</title>
{% endblock title %}

{% block subbreadcrumbs %}
  <li class="is-active"><a href='#'>{{pioneer.publisher.name|title}}</a></li>
  <li class="is-active"><a href='#'>Detail</a></li>
{% endblock subbreadcrumbs %}

{% block content %}
  <h1>Pioneer's Detail</h1>

  <div class="field is-grouped is-pulled-right" id="delete-button-app">
    <div class="control">
      <form id="form--{{ pioneer.pk }}" action='{% url "pioneering:delete" pioneer.pk %}' method="POST" @submit.prevent="confirmDelete">
        {% csrf_token %}
        <button class="button is-outlined" type="submit" form="form--{{ pioneer.pk }}" :disabled="disabled">{% include "_snippets/icon_trash.html" %}</button>
      </form>
    </div>

    <div class="control">
      <a href='{% url "pioneering:update" pioneer.slug %}'><button class="button is-outlined">{% include "_snippets/icon_edit.html" %}</button></a>
    </div>
  </div>
  
  <p class="is-size-3">{{ pioneer.publisher.name|upper }}</p>
  <p>Code: {{ pioneer.code }}</p>
  <p>Status: {% if pioneer.is_active %}{% include "_snippets/icon_check.html" %}{% else %}{% include "_snippets/icon_times.html" with color='has-text-danger' %}{% endif %}</p>

  <section class="section">
    <h2>Pioneering Details</h2>
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Type</th>
          <th>Start</th>
          <th>End</th>
        </tr>
      </thead>
      <tbody>
        {% if pioneer.details.all %}
          {% for detail in pioneer.details.all %}
          <tr>
            <td>{{detail.pioneer_type}}</td>
            <td>{{detail.date_start}}</td>
            <td>{{detail.date_end}}</td>
          </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="3" class="has-text-centered">No data available. Please create one.</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </section>
{% endblock content %}

{% block vueinstance %}
    <script src="{% static "deleteButtonApp.js" %}"></script>
{% endblock vueinstance %}

congregationms/templates/pioneering/pioneer_form.html
{% extends "pioneering/base.html" %}

{% block title %}
  {% if pioneer %} 
    <title>Pioneer Edit | {{ pioneer.publisher.name|title }}</title> 
  {% else %} 
    <title>Pioneer New</title>  
  {% endif %}
{% endblock title %}

{% block subbreadcrumbs %}
  {% if pioneer %}
    <li><a href='{% url "pioneering:detail" pioneer.slug %}'>{{ pioneer.publisher.name|title }}</a></li>
    <li class="is-active"><a href='#'>Edit</a></li>  
  {% else %}
    <li class="is-active"><a href='#'>New</a></li>  
  {% endif %}
{% endblock subbreadcrumbs %}

{% block content %}
  {% if pioneer %} 
    <h1>Pioneer Edit</h1>
    <p class="is-size-3">Edit Pioneer Profile</p>  
  {% else %} 
    <h1>Pioneer New</h1>
    <p class="is-size-3">Create a New Pioneer Profile</p>  
  {% endif %}

    <form method="POST">
      {% csrf_token %}
      <div class="field">
        <label class="label">{{form.publisher.label}}</label>
        <div class="control">
          <div class="select is-fullwidth">
            {{form.publisher}}
          </div>
        {{form.publisher.errors}}
        </div>
      </div>
      <div class="field">
        <label class="label">{{form.code.label}}</label>
        <div class="control">
          <input class="input" type="text" name="code" value="{{ form.code.value|default:'' }}" required>
        {{form.code.errors}}
        </div>
      </div>
      {% if pioneer %}  
          <label class="checkbox" for="{{form.is_active.id_for_label}}">
            Active
            <input type="checkbox" disabled {% if is_active %}checked{% endif %}>
          </label>
      {% endif %}


      {# group members #}
      <section class="section">
        <h2>Pioneering Details</h2>
        {{ details.management_form }}
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th class="has-text-centered">Type</th>
              <th class="has-text-centered">Date Start</th>
              <th class="has-text-centered">Date End</th>
              <th class="has-text-centered">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for form in details %}
              <tr>
                <td>
                  <div class="select is-fullwidth">
                    {{form.pioneer_type}}
                  </div>
                </td>

                <td>
                  <input class="input is-fullwidth" type="date" name="{{form.date_start.html_name}}" id="{{form.date_start.id_for_label}}" value="{{form.date_start.value|date:'Y-m-d'}}">
                </td>

                <td>
                  <input class="input is-fullwidth" type="date" name="{{form.date_end.html_name}}" id="{{form.date_end.id_for_label}}" value="{{form.date_end.value|date:'Y-m-d'}}">
                  {{form.id}}
                  {{form.pioneer}}
                </td>
                <td>
                  {% if details.can_delete %}
                    {{form.DELETE}} 
                  {% else %}
                    <input type="checkbox" disabled>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </section>

      {% if pioneer %}
        {% include "_snippets/button_save.html" %}
      {% else %}
        {% include "_snippets/button_create.html" %}
      {% endif %}
      
    </form>
{% endblock content %}

congregationms/templates/pioneering/pioneer_list.html
{% extends "pioneering/base.html" %}

{% block title %}
  <title>Pioneers</title>  
{% endblock title %}

{% block content %}
  <h1>Pioneers List</h1>
  <a href='{% url "pioneering:create" %}'>{% include "_snippets/button_new.html" %}</a>
  <p>Create and maintin records of the pioneers in your congregation.</p>
  <p>In this module, a "Pioneer" could be a Regular Pioneer (RP), Special Pioneer (SP), or Auxillary Pioneer.</p><br>

  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-centered">Publisher</th>
        <th class="has-text-centered" title="Auxi/RP/SP">Active</th>
        <th class="has-text-centered">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for pioneer in pioneers %}
        <tr>
          <td>{{ pioneer.publisher.name|title }}</td>
          <td class="has-text-centered">
            {% if  pioneer.is_active %}
                {% include "_snippets/icon_check.html" %}
            {% else %}
              {% include "_snippets/icon_times.html" %}
            {% endif %}
          </td>
          <td>
            <a href='{% url "pioneering:detail" pioneer.slug %}'><span class="button is-outlined">{% include "_snippets/icon_view.html" %}</span></a>
            <a href='{% url "pioneering:update" pioneer.slug %}'><span class="button is-outlined">{% include "_snippets/icon_edit.html" %}</span></a></td>
          </td>
        </tr>
      {% endfor %}

      {% if not pioneers %}
        <tr>
          <td colspan="3" class="has-text-centered">No members. Please <a href="{% url 'pioneering:create' %}"><u>add</u></a>.</td>
        </tr>  
      {% endif %}
    </tbody>
  </table><br>
{% endblock content %}